{"timestamp":"2025-10-27T15:48:50.991420Z","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-27T15:48:50.993340Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/test_http_connection_dag.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-27T15:48:51.067631Z","level":"warning","event":"The `airflow.hooks.base.BaseHook` attribute is deprecated. Please use `'airflow.sdk.bases.hook.BaseHook'`.","category":"DeprecatedImportWarning","filename":"/opt/airflow/dags/test_http_connection_dag.py","lineno":3,"logger":"py.warnings"}
{"timestamp":"2025-10-27T15:48:51.068028Z","level":"warning","event":"The `airflow.operators.python.PythonOperator` attribute is deprecated. Please use `'airflow.providers.standard.operators.python.PythonOperator'`.","category":"DeprecatedImportWarning","filename":"/opt/airflow/dags/test_http_connection_dag.py","lineno":4,"logger":"py.warnings"}
{"timestamp":"2025-10-27T15:48:51.109951Z","level":"info","event":"[HttpHook] base_url: ''","logger":"task.stdout"}
{"timestamp":"2025-10-27T15:48:51.148486Z","level":"info","event":"[BaseHook] host: 'host.docker.internal'","logger":"task.stdout"}
{"timestamp":"2025-10-27T15:48:51.148939Z","level":"info","event":"[BaseHook] schema: 'http'","logger":"task.stdout"}
{"timestamp":"2025-10-27T15:48:51.149394Z","level":"info","event":"[BaseHook] port: '8079'","logger":"task.stdout"}
{"timestamp":"2025-10-27T15:48:51.149666Z","level":"info","event":"[BaseHook] extra: 'None'","logger":"task.stdout"}
{"timestamp":"2025-10-27T15:48:51.149907Z","level":"info","event":"[BaseHook] get_uri(): 'http://host.docker.internal:8079/http'","logger":"task.stdout"}
{"timestamp":"2025-10-27T15:48:51.150150Z","level":"info","event":"[Resolved] Base URL derived: 'host.docker.internal'","logger":"task.stdout"}
{"timestamp":"2025-10-27T15:48:51.323398Z","level":"warning","event":"HTTPConnectionPool(host='host.docker.internal', port=8079): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8fd0f19790>: Failed to establish a new connection: [Errno 111] Connection refused')) Tenacity will retry to execute the operation","logger":"airflow.task.hooks.airflow.providers.http.hooks.http.HttpHook","filename":"http.py","lineno":356}
{"timestamp":"2025-10-27T15:48:51.323701Z","level":"info","event":"Done. Returned value was: None","logger":"airflow.task.operators.airflow.providers.standard.operators.python.PythonOperator","filename":"python.py","lineno":218}
{"timestamp":"2025-10-27T15:48:51.324760Z","level":"info","event":"Connectivity test failed: HTTPConnectionPool(host='host.docker.internal', port=8079): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8fd0f19790>: Failed to establish a new connection: [Errno 111] Connection refused'))","logger":"task.stdout"}
